title: Astronomía Para Niños # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sitio donde compartiré información sobre las charlas GRATIS de astronomía para niños (y grandes con corazón de niños).  
  <br><br>
  Soy astrofísica planetaría y profesora de la Universidad de Toronto.
  
  <br><br>
  <a href="https://www.linkedin.com/in/diana-valencia-3470342/">LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.twitter.com/valencia_planet">Síganme en Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-163592769-1 # your Google Analytics tracking ID here
