title: Diana Valencia # your name (or website title) here
logo: "/images/me.pdf?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Soy astrofísica planetaría y profesora de la Universidad de Toronto.
  <br><br>
  Este es un sitio donde compartiré información sobre las charlas GRATIS de astronomía para niños (y grandes con corazón de niños).  
  <br><br>
  <a href="https://www.linkedin.com/in/diana-valencia-3470342/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-163592769-1 # your Google Analytics tracking ID here
